import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "ReactWeb",
  description: "Generated by ReactDev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="d-flex flex-column" suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
